"""initial_schema

Revision ID: 585e793a6d66
Revises: 
Create Date: 2026-04-10 19:48:18.694546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585e793a6d66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('registrationDate', sa.DateTime(), nullable=False),
    sa.CheckConstraint("email LIKE '%_@_%._%'", name='ck_accounts_email_format'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('accountID', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('photoUrl', sa.String(length=1024), nullable=True),
    sa.CheckConstraint("username <> ''", name='ck_users_username_not_empty'),
    sa.ForeignKeyConstraint(['accountID'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accountID')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('friendships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userOneID', sa.Uuid(), nullable=False),
    sa.Column('userTwoID', sa.Uuid(), nullable=False),
    sa.Column('acceptedAt', sa.DateTime(), nullable=False),
    sa.CheckConstraint('"userOneID" <> "userTwoID"', name='ck_friendships_distinct_users'),
    sa.ForeignKeyConstraint(['userOneID'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userTwoID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userOneID', 'userTwoID', name='uq_friendship_pair')
    )
    op.create_index('ix_friendships_accepted_at', 'friendships', ['acceptedAt'], unique=False)
    op.create_index('ix_friendships_user_pair', 'friendships', ['userOneID', 'userTwoID'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fromUserID', sa.Uuid(), nullable=False),
    sa.Column('toUserID', sa.Uuid(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.CheckConstraint('"fromUserID" <> "toUserID"', name='ck_invitations_distinct_users'),
    sa.ForeignKeyConstraint(['fromUserID'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['toUserID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fromUserID', 'toUserID', name='uq_invitation_pair')
    )
    op.create_index('ix_invitations_from_date', 'invitations', ['fromUserID', 'date'], unique=False)
    op.create_index('ix_invitations_to_date', 'invitations', ['toUserID', 'date'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userID', sa.Uuid(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_userID'), 'notifications', ['userID'], unique=False)
    op.create_index('ix_notifications_user_active', 'notifications', ['userID', 'active'], unique=False)
    op.create_index('ix_notifications_user_date', 'notifications', ['userID', 'date'], unique=False)
    op.create_table('task_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ownerID', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('taskCount', sa.Integer(), nullable=False),
    sa.Column('isBingo', sa.Boolean(), nullable=False),
    sa.Column('privacy', sa.Enum('PRIVATE', 'PUBLIC', name='privacy_level'), nullable=False),
    sa.Column('inviteCode', sa.String(length=64), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.CheckConstraint("name <> ''", name='ck_task_groups_name_not_empty'),
    sa.CheckConstraint('"taskCount" >= 0', name='ck_task_groups_task_count_non_negative'),
    sa.ForeignKeyConstraint(['ownerID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_groups_ownerID'), 'task_groups', ['ownerID'], unique=False)
    op.create_index('ix_task_groups_owner_created', 'task_groups', ['ownerID', 'createdAt'], unique=False)
    op.create_table('competitive_task_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cooperative_task_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userID', sa.Uuid(), nullable=False),
    sa.Column('groupID', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'ADMIN', 'OWNER', name='group_role'), nullable=False),
    sa.Column('joinedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['groupID'], ['task_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userID', 'groupID', name='uq_group_member_user_group')
    )
    op.create_index(op.f('ix_group_members_groupID'), 'group_members', ['groupID'], unique=False)
    op.create_index('ix_group_members_group_active', 'group_members', ['groupID', 'active'], unique=False)
    op.create_index(op.f('ix_group_members_userID'), 'group_members', ['userID'], unique=False)
    op.create_index('ix_group_members_user_active', 'group_members', ['userID', 'active'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ownerID', sa.Uuid(), nullable=True),
    sa.Column('groupID', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('goal', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='task_status'), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.CheckConstraint("name <> ''", name='ck_tasks_name_not_empty'),
    sa.ForeignKeyConstraint(['groupID'], ['task_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ownerID'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_groupID'), 'tasks', ['groupID'], unique=False)
    op.create_index('ix_tasks_group_status', 'tasks', ['groupID', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_ownerID'), 'tasks', ['ownerID'], unique=False)
    op.create_index('ix_tasks_owner_group', 'tasks', ['ownerID', 'groupID'], unique=False)
    op.create_table('challenge_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endless_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one_time_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repeatable_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='time_interval'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_params',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('taskID', sa.Uuid(), nullable=False),
    sa.Column('photoRequired', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['taskID'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_params_taskID'), 'task_params', ['taskID'], unique=True)
    op.create_table('task_progresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userID', sa.Uuid(), nullable=True),
    sa.Column('taskID', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['taskID'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userID', 'taskID', name='uq_task_progress_user_task')
    )
    op.create_index(op.f('ix_task_progresses_taskID'), 'task_progresses', ['taskID'], unique=False)
    op.create_index('ix_task_progresses_task_type', 'task_progresses', ['taskID', 'type'], unique=False)
    op.create_index(op.f('ix_task_progresses_userID'), 'task_progresses', ['userID'], unique=False)
    op.create_index('ix_task_progresses_user_task', 'task_progresses', ['userID', 'taskID'], unique=False)
    op.create_table('challenge_task_progresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task_progresses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endless_task_progresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task_progresses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('one_time_task_progresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task_progresses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userID', sa.Uuid(), nullable=False),
    sa.Column('TaskProgressID', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('photoUrl', sa.String(length=1024), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['TaskProgressID'], ['task_progresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_entries_TaskProgressID'), 'progress_entries', ['TaskProgressID'], unique=False)
    op.create_index('ix_progress_entries_progress_created', 'progress_entries', ['TaskProgressID', 'createdAt'], unique=False)
    op.create_index(op.f('ix_progress_entries_userID'), 'progress_entries', ['userID'], unique=False)
    op.create_index('ix_progress_entries_user_created', 'progress_entries', ['userID', 'createdAt'], unique=False)
    op.create_table('repeatable_task_progresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['task_progresses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('userID', sa.Uuid(), nullable=False),
    sa.Column('progressEntryID', sa.Uuid(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['progressEntryID'], ['progress_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_progressEntryID'), 'comments', ['progressEntryID'], unique=False)
    op.create_index('ix_comments_progress_date', 'comments', ['progressEntryID', 'date'], unique=False)
    op.create_index(op.f('ix_comments_userID'), 'comments', ['userID'], unique=False)
    op.create_index('ix_comments_user_date', 'comments', ['userID', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_user_date', table_name='comments')
    op.drop_index(op.f('ix_comments_userID'), table_name='comments')
    op.drop_index('ix_comments_progress_date', table_name='comments')
    op.drop_index(op.f('ix_comments_progressEntryID'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('repeatable_task_progresses')
    op.drop_index('ix_progress_entries_user_created', table_name='progress_entries')
    op.drop_index(op.f('ix_progress_entries_userID'), table_name='progress_entries')
    op.drop_index('ix_progress_entries_progress_created', table_name='progress_entries')
    op.drop_index(op.f('ix_progress_entries_TaskProgressID'), table_name='progress_entries')
    op.drop_table('progress_entries')
    op.drop_table('one_time_task_progresses')
    op.drop_table('endless_task_progresses')
    op.drop_table('challenge_task_progresses')
    op.drop_index('ix_task_progresses_user_task', table_name='task_progresses')
    op.drop_index(op.f('ix_task_progresses_userID'), table_name='task_progresses')
    op.drop_index('ix_task_progresses_task_type', table_name='task_progresses')
    op.drop_index(op.f('ix_task_progresses_taskID'), table_name='task_progresses')
    op.drop_table('task_progresses')
    op.drop_index(op.f('ix_task_params_taskID'), table_name='task_params')
    op.drop_table('task_params')
    op.drop_table('repeatable_tasks')
    op.drop_table('one_time_tasks')
    op.drop_table('endless_tasks')
    op.drop_table('challenge_tasks')
    op.drop_index('ix_tasks_owner_group', table_name='tasks')
    op.drop_index(op.f('ix_tasks_ownerID'), table_name='tasks')
    op.drop_index('ix_tasks_group_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_groupID'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_group_members_user_active', table_name='group_members')
    op.drop_index(op.f('ix_group_members_userID'), table_name='group_members')
    op.drop_index('ix_group_members_group_active', table_name='group_members')
    op.drop_index(op.f('ix_group_members_groupID'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_table('cooperative_task_groups')
    op.drop_table('competitive_task_groups')
    op.drop_index('ix_task_groups_owner_created', table_name='task_groups')
    op.drop_index(op.f('ix_task_groups_ownerID'), table_name='task_groups')
    op.drop_table('task_groups')
    op.drop_index('ix_notifications_user_date', table_name='notifications')
    op.drop_index('ix_notifications_user_active', table_name='notifications')
    op.drop_index(op.f('ix_notifications_userID'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_invitations_to_date', table_name='invitations')
    op.drop_index('ix_invitations_from_date', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_friendships_user_pair', table_name='friendships')
    op.drop_index('ix_friendships_accepted_at', table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    op.execute('DROP TYPE IF EXISTS time_interval')
    op.execute('DROP TYPE IF EXISTS task_status')
    op.execute('DROP TYPE IF EXISTS group_role')
    op.execute('DROP TYPE IF EXISTS privacy_level')
    # ### end Alembic commands ###
